yarnPath: .yarn/releases/yarn-4.1.1.cjs

nodeLinker: node-modules
npmPublishAccess: "public"

npmRegistries:
    "https://registry.npmjs.org":
        npmAuthToken: "${npm_token}"

npmScopes:
    abcdefpackage:
        npmRegistryServer: "https://registry.npmjs.org/"
