name: Node.js Package

on:
    push:
        branches:
            - main

jobs:
    build-and-publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/
            - name: Set SHAs
              uses: nrwl/nx-set-shas@v4
            - name: install dependencies
              run: |
                  npm install -g yarn
                  yarn
            - name: check changeset file
              id: check-changeset
              run: |

                  if [ $(ls .changeset | wc -l) -eq 2 ]; then
                    exit 1
                  else
                    exit 0
                  fi
              continue-on-error: true
            - name: build
              id: build
              run: |
                  yarn build
            - name: Versioning and publish
              if: steps.check-changeset.outcome != 'success'
              run: |
                  yarn run patch:affected ${{ env.NX_BASE }}
                  yarn run publish:affected
            - name: Update Versions
              if: steps.check-change-set.outcome == 'success'
              run: echo 'SUCCESS'
